SP-Python-Essentials-DP: c++/CEP1-MOD1T/CEP1-MOD1T.cpp File Reference
CEP1-MOD1T.cpp File Reference
#include "CEP1-MOD1T.h"
Functions
int main ()
Variables
MyClass sus
Function Documentation
main()
int main ()
Definition at line 10 of file CEP1-MOD1T.cpp.
{
    cout << "Hello CMake." << endl;
    sus.quiz();
    sus.quiz2();
    sus.quiz3();
    sus.quiz4();
    sus.quiz5();
    sus.quiz6();
    sus.quiz7();
    sus.quiz8();
    sus.quiz9(8);
    sus.quiz10();
    sus.quiz11();
    sus.quiz12();
    return 0;
}
References MyClass::quiz(), MyClass::quiz10(), MyClass::quiz11(), MyClass::quiz12(), MyClass::quiz2(), MyClass::quiz3(), MyClass::quiz4(), MyClass::quiz5(), MyClass::quiz6(), MyClass::quiz7(), MyClass::quiz8(), MyClass::quiz9(), and sus.
Variable Documentation
sus
MyClass sus
Definition at line 8 of file CEP1-MOD1T.cpp.
Referenced by main().