SP-Python-Essentials-DP: c++/CPP-ESS1-PS1UT/CPP-ESS1-PS1UT.cpp File Reference
CPP-ESS1-PS1UT.cpp File Reference
#include "CPP-ESS1-PS1UT.h"
#include "CPP-ESS1-PS1USS.h"
Functions
int main ()
Variables
MyClass sus
MyClasss sus2
Function Documentation
main()
int main ()
Definition at line 13 of file CPP-ESS1-PS1UT.cpp.
{
    sus.qz1();
    sus.qz2();
    sus.qz3();
    sus.qz4();
    sus.qz5();
    sus.qz6();
    sus.qz7();
    sus.qz8();
    sus.qz9();
    sus.qz10();
    sus.qz11();
    sus.qz12();
    sus.qz13();
    //sus.qz14();
    cout << "------------" << endl;
    cout << "------------" << endl;
    sus2.qz0();
    sus2.qz1();
    sus2.qz2();
    sus2.qz3();
    sus2.qz4();
    sus2.qz5();
    sus2.qz6();
    sus2.qz7();
    sus2.qz8();
    sus2.qz9();
    sus2.qz10();
    sus2.qz11();
    sus2.qz12();
    cout << "Hello CMake." << endl;
    return 0;
}
References MyClasss::qz0(), MyClass::qz1(), MyClasss::qz1(), MyClass::qz10(), MyClasss::qz10(), MyClass::qz11(), MyClasss::qz11(), MyClass::qz12(), MyClasss::qz12(), MyClass::qz13(), MyClass::qz2(), MyClasss::qz2(), MyClass::qz3(), MyClasss::qz3(), MyClass::qz4(), MyClasss::qz4(), MyClass::qz5(), MyClasss::qz5(), MyClass::qz6(), MyClasss::qz6(), MyClass::qz7(), MyClasss::qz7(), MyClass::qz8(), MyClasss::qz8(), MyClass::qz9(), MyClasss::qz9(), sus, and sus2.
Variable Documentation
sus
MyClass sus
Definition at line 9 of file CPP-ESS1-PS1UT.cpp.
Referenced by main().
sus2
MyClasss sus2
Definition at line 11 of file CPP-ESS1-PS1UT.cpp.
Referenced by main().