SP-Python-Essentials-DP: c++/CPP-ESS1-PS1UT/CPP-ESS1-PS1USS.h File Reference
CPP-ESS1-PS1USS.h File Reference
#include <iostream>
#include <string>
#include <vector>
Classes
class MyClasss
Namespaces
namespace Universe
Functions
string replicate (string s="", int r=1)
int op (int i, int j=1)
int op (char a, char b)
int op (float x, float y)
void swap (float *x, float *y)
double eval (double x)
void use (double n)
Variables
int Universe::Galaxy = 1
int Universe::Planet = Galaxy + 2
Function Documentation
eval()
double eval (double x)
Definition at line 136 of file CPP-ESS1-PS1USS.h.
{
    return x / (.5 * x);
}
References 2::x.
Referenced by use().
op() [1/3]
int op (char a, char b)
Definition at line 77 of file CPP-ESS1-PS1USS.h.
                       {
    return b - a;
}
References 2::a, and Cisco::b.
op() [2/3]
int op (float x, float y)
Definition at line 80 of file CPP-ESS1-PS1USS.h.
{
    return x / y;
}
References 2::x, and 2::y.
op() [3/3]
int op (int i, int j = 1)
Definition at line 74 of file CPP-ESS1-PS1USS.h.
{
    return i * j;
}
References Cisco::i.
replicate()
string replicate (string s = "", int r = 1)
Definition at line 38 of file CPP-ESS1-PS1USS.h.
{
    string t;
    while (r--)
        t += s;
    return t;
}
swap()
void swap (float * x, float * y)
Definition at line 91 of file CPP-ESS1-PS1USS.h.
{
    float z = *x;
    *x = *y;
    *y = z;
}
References 2::x, 2::y, and quiz::z.
Referenced by MyClasss::qz4().
use()
void use (double n)
Definition at line 140 of file CPP-ESS1-PS1USS.h.
{
    int v = 1 / n;
    v = eval(v);
    cout << v;
}
References eval().
Referenced by MyClasss::qz8().