SP-Python-Essentials-DP: MyClass Class Reference
MyClass Class Reference
#include <CEP1-MOD1T.h>
Public Member Functions
void quiz2 ()
void quiz ()
void quiz3 ()
void quiz4 ()
void quiz5 ()
void quiz6 ()
void quiz7 ()
void quiz8 ()
void quiz9 (int i)
void quiz10 ()
void quiz11 ()
void quiz12 ()
void quiz13 ()
void qz1 ()
void qz2 ()
void qz3 ()
void qz4 ()
void qz5 ()
void qz6 ()
void qz7 ()
void qz8 ()
void qz9 ()
void qz10 ()
void qz11 ()
void qz12 ()
void qz13 ()
void qz14 ()
void qz15 ()
void qz16 ()
void qz0 ()
void qz1 ()
void qz2 ()
void qz3 ()
void qz4 ()
void qz5 ()
void qz6 ()
void qz7 ()
void qz8 ()
void qz9 ()
void qz10 ()
void qz11 ()
void qz12 ()
void qz13 ()
void qz14 ()
void qz15 ()
void myClass ()
void temp ()
void qz2 ()
void qz3 ()
void qz4 ()
void qz5 ()
void qz6 ()
void qz7 ()
void qz8 ()
void qz9 ()
void qz10 ()
void myClasss ()
void MyClasss ()
void qz0 ()
void qz1 ()
void qz2 ()
void qz3 ()
void qz4 ()
void qz5 ()
void qz6 ()
void qz7 ()
void qz8 ()
void qz9 ()
void qz10 ()
void qz12 ()
void qz13 ()
void qz11 ()
Detailed Description
Definition at line 12 of file CEP1-MOD1T.h.
Member Function Documentation
myClass()
void MyClass::myClass ()
Definition at line 32 of file cpp-ess1-mod2.h.
{
    int i = 2;
    float a = 3;
    bool f1 = i > a, f2 = a > i, f3 = a / i > i / a;
    if (f3)
        if (f2)
            i += 1;
        else
            i += 2;
    else if (f1)
        i += 3;
    else
        i += 4;
    cout << i << endl;
    cout <<"1" <<"\n"<< endl;
}
References 2::a, and Cisco::i.
Referenced by main().
myClasss()
void MyClass::myClasss ()
MyClasss()
void MyClass::MyClasss ()
quiz()
void MyClass::quiz ()
Definition at line 67 of file CEP1-MOD1T.h.
{
    cout << -1e-1 << endl;
    cout << "s" << endl;
    cout << 0x1A << endl;
    cout << "/n2" << endl;
}
Referenced by main().
quiz10()
void MyClass::quiz10 ()
Definition at line 135 of file CEP1-MOD1T.h.
                     {
    float x = 2.5;
    cout << "/n10" << endl;
    //cin >> x;
    cout << scientific << "x" << endl;
}
References 2::x.
Referenced by main().
quiz11()
void MyClass::quiz11 ()
Definition at line 146 of file CEP1-MOD1T.h.
                     {
    cout << "/n11" << endl;
    cout << 0E1 << endl;
}
Referenced by main().
quiz12()
void MyClass::quiz12 ()
Definition at line 153 of file CEP1-MOD1T.h.
                     {
    int k = 1 % 2 + 4 % 2;
    cout << "/n12" << endl;
    cout << k << endl;
}
Referenced by main().
quiz13()
void MyClass::quiz13 ()
Definition at line 160 of file CEP1-MOD1T.h.
                     {
    cout << "/n13" << endl;
    // cout << 018 << endl;
}
quiz2()
void MyClass::quiz2 ()
Definition at line 44 of file CEP1-MOD1T.h.
{
    int i = 3, j = 2, k = -1;
    if (i > 0) {
        if(j <=0){
            if (k < 0)
                k++;
            if (k <= 0)
                k--;
        }
        if (j > 0)
            i++;
    }
if (i <= 0)
    j++;
k = i + j + k;
cout << k << endl;
cout << "/n1" << endl;
}
References Cisco::i.
Referenced by main().
quiz3()
void MyClass::quiz3 ()
Definition at line 75 of file CEP1-MOD1T.h.
{
    int i = 3, j, k;
    if (i > 0)  j = 2 + i * i;
    if (i <= 0) j = 2 * i - 1;
    if (j >= 0) k = j % i + 2;
    if (j < 0)  k = i % j + 2;
    if (k < 0) k = k % i % j;
    if (k >= 0)k = j % i % k;
    cout << k << endl;
    cout << "/n" << endl;
    cout << "/n3" << endl;
}
References Cisco::i.
Referenced by main().
quiz4()
void MyClass::quiz4 ()
Definition at line 89 of file CEP1-MOD1T.h.
                    {
    float x = 1. / 2. + 2. / 4.;
    cout << x << endl;
    cout << "/n4" << endl;
}
References 2::x.
Referenced by main().
quiz5()
void MyClass::quiz5 ()
Definition at line 95 of file CEP1-MOD1T.h.
                    {
    float x = 1.0 / 4.0;
    int i = x;
    cout << x << endl;
    cout << "/n5" << endl;
}
References Cisco::i, and 2::x.
Referenced by main().
quiz6()
void MyClass::quiz6 ()
Definition at line 102 of file CEP1-MOD1T.h.
                    {
    int i = 3, j = ++i, k = ++i;
    cout << k << j << i << endl;
    cout << "/n6" << endl;
}
References Cisco::i.
Referenced by main().
quiz7()
void MyClass::quiz7 ()
Definition at line 108 of file CEP1-MOD1T.h.
                    {
    int i = 1;
    int j = ++i;
    int k = j++;
    cout << k << endl;
    cout << "/n7" << endl;
}
References Cisco::i.
Referenced by main().
quiz8()
void MyClass::quiz8 ()
Definition at line 117 of file CEP1-MOD1T.h.
                    {
    int i = 3, j = ++i, k = ++i;
    i = 5;
    //cin >> i;
    cout << k + i << j - i << i * i << endl;
    cout << "/n8"<< endl;
}
References Cisco::i.
Referenced by main().
quiz9()
void MyClass::quiz9 (int i)
Definition at line 125 of file CEP1-MOD1T.h.
{
    cout << "/n9" << endl;
    //cin >> i;
    cout << i << hex << i + i << oct << i << endl;
}
References Cisco::i.
Referenced by main().
qz0() [1/2]
void MyClass::qz0 ()
Definition at line 31 of file CEP1-MOD4T.h.
                 {
    cout << "H" << endl;
    cout << "1 \n" << endl;
}
qz0() [2/2]
void MyClass::qz0 ()
qz1() [1/3]
void MyClass::qz1 ()
Definition at line 33 of file CEP1-MOD2T.h.
{
    for (float val = -10.0; val < 20.0; val = -val * 2)
        cout << "*";
    cout << " ";
    cout << "1" << endl;
}
Referenced by main().
qz1() [2/3]
void MyClass::qz1 ()
qz1() [3/3]
void MyClass::qz1 ()
qz10() [1/4]
void MyClass::qz10 ()
Definition at line 149 of file CEP1-MOD2T.h.
{
    int a = 1, b = 2;
    int c = a << b;
    int d = 1 << c;
    int e = d >> d;
    cout << e;
    cout << " ";
    cout << "10" << endl;
}
References 2::a, Cisco::b, and Cisco::c.
Referenced by main().
qz10() [2/4]
void MyClass::qz10 ()
qz10() [3/4]
void MyClass::qz10 ()
qz10() [4/4]
void MyClass::qz10 ()
qz11() [1/3]
void MyClass::qz11 ()
Definition at line 161 of file CEP1-MOD2T.h.
{
    int i = 0, j = i++, k = --i;
    if (i > 0){
        j++;
        k++;
    }
    else {
        k++;
        i++;
    }
    if (k == 0) {
        i++;
        j++;
    }
    else {
        if (k > 0)
            k--;
        else
            k++;
        i++;
    }
    cout << i * j *k;
    cout << " ";
    cout << "11" << endl;
}
References Cisco::i.
Referenced by main().
qz11() [2/3]
void MyClass::qz11 ()
qz11() [3/3]
void MyClass::qz11 ()
qz12() [1/3]
void MyClass::qz12 ()
Definition at line 193 of file CEP1-MOD2T.h.
{
    int i = 3, j = 0;
    do {
        i--;
        j++;
    } while (i >= 0);
    cout << j;
    cout << " ";
    cout << "12" << endl;
}
References Cisco::i.
Referenced by main().
qz12() [2/3]
void MyClass::qz12 ()
qz12() [3/3]
void MyClass::qz12 ()
qz13() [1/3]
void MyClass::qz13 ()
Definition at line 206 of file CEP1-MOD2T.h.
{
    struct s
    {
        int t;
    };
    struct SS
    {
        s t;
    };
    vector<SS> t = { {1},{2} };
    cout << t[0].t.t << t[1].t.t;
    cout << " ";
    cout << "13" << endl;
}
Referenced by main().
qz13() [2/3]
void MyClass::qz13 ()
qz13() [3/3]
void MyClass::qz13 ()
qz14() [1/2]
void MyClass::qz14 ()
Definition at line 225 of file CEP1-MOD2T.h.
                   {
    vector<int> t = { 8,4,3,2,1 };
    int i;
    for (i = t[4]; i < t[3]; i++)
        t[i - 1] = -t[3];
    cout << i;
    cout << " ";
    cout << "14" << endl;
}
References Cisco::i.
Referenced by main().
qz14() [2/2]
void MyClass::qz14 ()
qz15() [1/2]
void MyClass::qz15 ()
Definition at line 237 of file CEP1-MOD2T.h.
                   {
    double big = 1e15;
    double small = 1e-15;
    cout << fixed << big + small;
    cout << " ";
    cout << "15" << endl;
}
Referenced by main().
qz15() [2/2]
void MyClass::qz15 ()
qz16()
void MyClass::qz16 ()
Definition at line 246 of file CEP1-MOD2T.h.
                   {
    vector<bool> t(2);
    for (int i = 0; i < 2; i++)
        t[1 - i] = !(i % 2);
    cout << t[0] && t[1];
    cout << " ";
    cout << "16" << endl;
}
References Cisco::i.
Referenced by main().
qz2() [1/4]
void MyClass::qz2 ()
Definition at line 41 of file CEP1-MOD2T.h.
{
    float val = 100.0;
    do {
        val = val / 5;
        cout << "*";
    } while (val > 1.0);
    cout << " ";
    cout << "2" << endl;
}
Referenced by main().
qz2() [2/4]
void MyClass::qz2 ()
qz2() [3/4]
void MyClass::qz2 ()
qz2() [4/4]
void MyClass::qz2 ()
qz3() [1/4]
void MyClass::qz3 ()
Definition at line 53 of file CEP1-MOD2T.h.
{
    vector<int> a = {2, 0, 1};
    vector<int> b = { 1,2,3 };
    for (int i = 0; i < 3; i++)
        b[a[i]] = b[2 - i];
    cout << b[0]<< b[2];
    cout << " ";
    cout << "3" << endl;
}
References 2::a, Cisco::b, and Cisco::i.
Referenced by main().
qz3() [2/4]
void MyClass::qz3 ()
qz3() [3/4]
void MyClass::qz3 ()
qz3() [4/4]
void MyClass::qz3 ()
qz4() [1/4]
void MyClass::qz4 ()
Definition at line 64 of file CEP1-MOD2T.h.
                  {
    int a = 1, b = 2;
    int c = a | b;
    int d = c & a;
    int e = d ^ 0;
    cout << e << d << c;
    cout << " ";
    cout << "4" << endl;
}
References 2::a, Cisco::b, and Cisco::c.
Referenced by main().
qz4() [2/4]
void MyClass::qz4 ()
qz4() [3/4]
void MyClass::qz4 ()
qz4() [4/4]
void MyClass::qz4 ()
qz5() [1/4]
void MyClass::qz5 ()
Definition at line 75 of file CEP1-MOD2T.h.
                  {
    struct Str
    {
        int in;
        char ch;
    };
    vector<Str> t = { {1,'a'},{2,'b'} };
    for (int i = 0; i < 2; i++)
        t[i].in += (t[1 - i].ch - t[i].ch);
    cout << t[0].in<< t[1].in;
    cout << " ";
    cout << "5" << endl;
}
References Cisco::i.
Referenced by main().
qz5() [2/4]
void MyClass::qz5 ()
qz5() [3/4]
void MyClass::qz5 ()
qz5() [4/4]
void MyClass::qz5 ()
qz6() [1/4]
void MyClass::qz6 ()
Definition at line 92 of file CEP1-MOD2T.h.
                  {
    vector<vector<int>> g = { {2,4},{3,6},{5,10} };
    for (int i = 1; i >= 0; i--)
        for (int j = 0; j < 2; j++)
            g[i][j] += g[j][i];
    cout << g[1][1];
    cout << " ";
    cout << "6" << endl;
}
References Cisco::i.
Referenced by main().
qz6() [2/4]
void MyClass::qz6 ()
qz6() [3/4]
void MyClass::qz6 ()
qz6() [4/4]
void MyClass::qz6 ()
qz7() [1/4]
void MyClass::qz7 ()
Definition at line 102 of file CEP1-MOD2T.h.
                  {
    int a = 2;
    switch (a<<a)
    {
    case 8: a++;
    case 4: a++;
    case 2: break;
    case 1: a--;
    }
    cout << a;
    cout << " ";
    cout << "7" << endl;
}
References 2::a.
Referenced by main().
qz7() [2/4]
void MyClass::qz7 ()
qz7() [3/4]
void MyClass::qz7 ()
qz7() [4/4]
void MyClass::qz7 ()
qz8() [1/4]
void MyClass::qz8 ()
Definition at line 116 of file CEP1-MOD2T.h.
                  {
    int i = 0, j = i++, k = --i;
    if (i > 0)
        j++;
    else
        k++;
    if (k == 0)
        i++;
    else
        k++;
    cout << i * j *k ;
    cout << " ";
    cout << "8" << endl;
}
References Cisco::i.
Referenced by main().
qz8() [2/4]
void MyClass::qz8 ()
qz8() [3/4]
void MyClass::qz8 ()
qz8() [4/4]
void MyClass::qz8 ()
qz9() [1/4]
void MyClass::qz9 ()
Definition at line 132 of file CEP1-MOD2T.h.
                  {
    struct Stru
    {
        int i1, i2;
        char c1, c2;
    };
    Stru a = { 1,2,'a','b' };
    Stru b = { 5, 6, 'x','y' };
    cout << static_cast<char>(b.c1 + a.i1);
    cout << static_cast<int>(a.c2 - a.c1);
    cout << static_cast<int>(b.c2 - b.c1);
    cout << " ";
    cout << "9" << endl;
}
References 2::a, and Cisco::b.
Referenced by main().
qz9() [2/4]
void MyClass::qz9 ()
qz9() [3/4]
void MyClass::qz9 ()
qz9() [4/4]
void MyClass::qz9 ()
temp()
void MyClass::temp ()
Definition at line 50 of file cpp-ess1-mod2.h.
{
    int i = 1;
    cout << i << endl;
    cout << "1" << endl;
}
References Cisco::i.
The documentation for this class was generated from the following files:
c++/CEP1-MOD1T/CEP1-MOD1T.h
c++/CEP1-MOD2T/CEP1-MOD2T.h
c++/CEP1-MOD4T/CEP1-MOD4T.h
c++/cpp-ess1-mod2/cpp-ess1-mod2.h
c++/CPP-ESS1-PS1UT/CPP-ESS1-PS1UT.h