SP-Python-Essentials-DP: MyClasss Class Reference
MyClasss Class Reference
#include <CEP1-MOD4T-1.h>
Public Member Functions
void qz0 ()
void qz1 ()
void qz2 ()
void qz3 ()
void qz4 ()
void qz5 ()
void qz6 ()
void qz0 ()
void qz1 ()
void qz2 ()
void qz3 ()
void qz4 ()
void qz5 ()
void qz6 ()
void qz7 ()
void qz8 ()
void qz9 ()
void qz10 ()
void qz11 ()
void qz12 ()
Detailed Description
Definition at line 8 of file CEP1-MOD4T-1.h.
Member Function Documentation
qz0() [1/2]
void MyClasss::qz0 ()
Definition at line 27 of file CEP1-MOD4T-1.h.
                  {
    S::A = S::A + 1; {
        using namespace S;
        ++B;
    }
    cout << S::B << S::A << endl;
    cout << "1 \n" << endl;
}
References S::A, and S::B.
Referenced by main().
qz0() [2/2]
void MyClasss::qz0 ()
qz1() [1/2]
void MyClasss::qz1 ()
Definition at line 52 of file CPP-ESS1-PS1USS.h.
{
    vector<char> test(5);
    char* chr1 = test.data() + 2, * chr2 = chr1 + 2;
    cout << "\n" << endl;
    cout << chr2 - test.data() << endl;
    cout << "1" << endl;
}
Referenced by main().
qz1() [2/2]
void MyClasss::qz1 ()
qz10()
void MyClasss::qz10 ()
Definition at line 162 of file CPP-ESS1-PS1USS.h.
{
    int i = 1, k = i & 0;
    do {
        k++;
        if (k > 1)
            i = k;
    } while (i < 2);
    cout << k << endl;
    cout << "10" << endl;
}
References Cisco::i.
Referenced by main().
qz11()
void MyClasss::qz11 ()
Definition at line 173 of file CPP-ESS1-PS1USS.h.
{
    int a = 0x02, b = 001;
    int c = a ^ b;
    int d = c | a;
    int e = d & 0;
    cout << e << endl;
    cout << "11" << endl;
}
References 2::a, Cisco::b, and Cisco::c.
Referenced by main().
qz12()
void MyClasss::qz12 ()
Definition at line 182 of file CPP-ESS1-PS1USS.h.
{
    vector<float*> ft = { new float[1],new float[2], new float[3] };
    for (int i = 0; i < 3; i++) {
        float* p = ft[i];
        *p = i;
    }
    cout << *ft[1];
    for (int i = 0; i < 3; i++) {
        delete[] ft[i];
    }
    cout << "HE" << endl;
    cout << "12" << endl;
}
References Cisco::i, and multiprocessing Process IDs::p.
Referenced by main().
qz2() [1/2]
void MyClasss::qz2 ()
Definition at line 37 of file CEP1-MOD4T-1.h.
                   {
    { using namespace S1;
//  S2::A = A + 1;
    }
    {using namespace S2;
//  S1::A = A + 1;
    }
    cout << S1::A << S2::A << endl;
    cout << "\n" << endl;
    cout << "1 \n" << endl;
}
References S1::A, and S2::A.
Referenced by main().
qz2() [2/2]
void MyClasss::qz2 ()
qz3() [1/2]
void MyClasss::qz3 ()
Definition at line 49 of file CEP1-MOD4T-1.h.
                  {
//  SpaceA::A = SpaceB::A = 1;
//  cout << A + 1 << endl;
    cout << "\n" << endl;
    cout << "3 \n" << endl;
}
Referenced by main().
qz3() [2/2]
void MyClasss::qz3 ()
qz4() [1/2]
void MyClasss::qz4 ()
Definition at line 98 of file CPP-ESS1-PS1USS.h.
{
    vector<float> t = { 3.,2.,1. };
    swap(&t[0], &t[2]);
    cout << "\n" << endl;
    cout << t[1] << endl;
    cout << "4::" << endl;
}
References swap().
Referenced by main().
qz4() [2/2]
void MyClasss::qz4 ()
qz5() [1/2]
void MyClasss::qz5 ()
Definition at line 108 of file CPP-ESS1-PS1USS.h.
{
    int k = 2 % 3 + 5 % 3;
    cout << "\n" << endl;
    cout << k;
    cout << "\n" << endl;
    cout << "5" << endl;
}
Referenced by main().
qz5() [2/2]
void MyClasss::qz5 ()
qz6() [1/2]
void MyClasss::qz6 ()
Definition at line 117 of file CPP-ESS1-PS1USS.h.
{
    float k = 1E-1;
    cout << "\n" << endl;
    cout << k ;
    cout << "\n" << endl;
    cout << "6" << endl;
}
Referenced by main().
qz6() [2/2]
void MyClasss::qz6 ()
qz7()
void MyClasss::qz7 ()
Definition at line 127 of file CPP-ESS1-PS1USS.h.
{
    vector<double> arr = { 1e-1,1e0,1e1 };
    double* ptr = arr.data() + 2;
    cout << "\n" << endl;
    cout << arr[1] - *ptr;
    cout << "\n" << endl;
    cout << "7" << endl;
}
Referenced by main().
qz8()
void MyClasss::qz8 ()
Definition at line 146 of file CPP-ESS1-PS1USS.h.
{
    cout << "\n" << endl;
    use(1.f);
    cout << "\n" << endl;
    cout << "8" << endl;
}
References use().
Referenced by main().
qz9()
void MyClasss::qz9 ()
Definition at line 153 of file CPP-ESS1-PS1USS.h.
{
    cout << "\n" << endl;
    float x = 1.0 / 5.0;
    int i = x;
    cout << i << endl;
    cout << "9" << endl;
}
References Cisco::i, and 2::x.
Referenced by main().
The documentation for this class was generated from the following files:
c++/CEP1-MOD4T/CEP1-MOD4T-1.h
c++/CPP-ESS1-PS1UT/CPP-ESS1-PS1USS.h