SP-Python-Essentials-DP: c++/CEP1-MOD4T/CEP1-MOD4T.cpp File Reference
CEP1-MOD4T.cpp File Reference
#include "CEP1-MOD4T.h"
#include "CEP1-MOD4T-1.h"
Functions
int main ()
Variables
MyClass sus
MyClasss sus2
Function Documentation
main()
int main ()
Definition at line 13 of file CEP1-MOD4T.cpp.
{
    cout << "sus" << endl;
    sus.qz1();
    sus.qz2();
    sus.qz3();
    sus.qz4();
    sus.qz5();
    sus.qz6();
    sus.qz7();
    cout << "sus2" << endl;
    sus2.qz0();
    //sus2.qz1();
    cout << "sus2" << endl;
    sus.qz8();
    sus.qz9();
    sus.qz10();
    sus.qz11();
    sus.qz12();
    sus.qz13();
    sus.qz14();
    sus.qz15();
    cout << "Hello CMake." << endl;
    return 0;
}
References MyClasss::qz0(), MyClass::qz1(), MyClass::qz10(), MyClass::qz11(), MyClass::qz12(), MyClass::qz13(), MyClass::qz14(), MyClass::qz15(), MyClass::qz2(), MyClass::qz3(), MyClass::qz4(), MyClass::qz5(), MyClass::qz6(), MyClass::qz7(), MyClass::qz8(), MyClass::qz9(), sus, and sus2.
Variable Documentation
sus
MyClass sus
Definition at line 9 of file CEP1-MOD4T.cpp.
Referenced by main().
sus2
MyClasss sus2
Definition at line 11 of file CEP1-MOD4T.cpp.
Referenced by main().