SP-Python-Essentials-DP: Python Namespace Reference
Python Namespace Reference
Functions
def liters_100km_to_miles_gallon (liters)
def miles_gallon_to_liters_100km (miles)
Variables
float Gallon = 3.785411784
float Mile = 1.609344
Function Documentation
liters_100km_to_miles_gallon()
def Python.liters_100km_to_miles_gallon (liters)
Definition at line 5 of file Python.Lab.4.3.1.10.py.
def liters_100km_to_miles_gallon(liters):
#
# Write your code here.
#
 us = 100 *3.785411784
 pre = 1.609344* liters
 gallon = us / pre
 return gallon
Referenced by miles_gallon_to_liters_100km().
miles_gallon_to_liters_100km()
def Python.miles_gallon_to_liters_100km (miles)
Definition at line 18 of file Python.Lab.4.3.1.10.py.
def miles_gallon_to_liters_100km(miles):
#
# Write your code here
#
 us = 100 *3.785411784
 pre = 1.609344* miles
 Liters = us / pre
 return Liters
print(liters_100km_to_miles_gallon(3.9))
print(liters_100km_to_miles_gallon(7.5))
print(liters_100km_to_miles_gallon(10.))
print(miles_gallon_to_liters_100km(60.3))
print(miles_gallon_to_liters_100km(31.4))
print(miles_gallon_to_liters_100km(23.5))
References liters_100km_to_miles_gallon(), and miles_gallon_to_liters_100km().
Referenced by miles_gallon_to_liters_100km().
Variable Documentation
Gallon
float Python.Gallon = 3.785411784
Definition at line 1 of file Python.Lab.4.3.1.10.py.
Mile
float Python.Mile = 1.609344
Definition at line 3 of file Python.Lab.4.3.1.10.py.