SP-Python-Essentials-DP: 4 Namespace Reference
4 Namespace Reference
Functions
def is_year_leap (year)
def days_in_month (year, month)
def day_of_year (year, month, day)
def is_prime (num)
Variables
list test_data = [1900, 2000, 2016, 1987]
list test_results = [False, True, True, False]
list yr = test_data[i]
end
def result = is_year_leap(yr)
list test_years = [1900, 2000, 2016, 1987]
list test_months = [2, 2, 1, 11]
list mo = test_months[i]
Function Documentation
day_of_year()
def 4.day_of_year (year, month, day)
Definition at line 45 of file 4.3.1.8 LAB Day of the year writing and using your own functions.py.
def day_of_year(year, month, day):
    date_val = date(year, month, day)
    year_month_day = date_val.toordinal() - date(date_val.year, 1, 1).toordinal() + 1
    print("\nDay of year: ", year_month_day, "\n")
    return year_month_day
print("\n")
print("\n")
print("\n")
print(day_of_year(2000, 12, 31))
References day_of_year().
Referenced by day_of_year().
days_in_month()
def 4.days_in_month (year, month)
Definition at line 34 of file 4.3.1.7 LAB How many days writing and using your own functions.py.
def days_in_month(year, month):
 print(calendar.monthrange(year,month)[1])
 days_month = calendar.monthrange(year,month)[1]
    #
    # Write your new code here.
    #
 print(days_month)
 return days_month
print("\n")
is_prime()
def 4.is_prime (num)
Definition at line 5 of file 4.3.1.9 LAB Prime numbers - how to find them .py.
def is_prime(num):
# Corner case
 if (num <= 1):
  return False
    # Check from 2 to sqrt(n)
 for i in range(2, int(sqrt(num))+1):
  if (num % i == 0):
    return False
 return True
References is_prime().
Referenced by is_prime().
is_year_leap()
def 4.is_year_leap (year)
Definition at line 6 of file 4.3.1.6 LAB A leap year writing your own functions.py.
def is_year_leap(year):
        if (year % 400 == 0) and (year % 100 == 0):
            print("{0} is a leap year".format(year))
            is_year = True
            pass
        # not divided by 100 means not a century year
        # year divided by 4 is a leap year
        elif (year % 4 == 0) and (year % 100 != 0):
            print("{0} is a leap year".format(year))
            is_year = True
            pass
        # if not divided by both 400 (century year) and 4 (not century year)
        # year is not leap year
        else:
            print("{0} is not a leap year".format(year))
            is_year = False
            pass
        return is_year
Variable Documentation
end
4.end
Definition at line 36 of file 4.3.1.6 LAB A leap year writing your own functions.py.
mo
list 4.mo = test_months[i]
Definition at line 51 of file 4.3.1.7 LAB How many days writing and using your own functions.py.
result
def 4.result = is_year_leap(yr)
Definition at line 37 of file 4.3.1.6 LAB A leap year writing your own functions.py.
test_data
list 4.test_data = [1900, 2000, 2016, 1987]
Definition at line 31 of file 4.3.1.6 LAB A leap year writing your own functions.py.
test_months
list 4.test_months = [2, 2, 1, 11]
Definition at line 47 of file 4.3.1.7 LAB How many days writing and using your own functions.py.
test_results
list 4.test_results = [False, True, True, False]
Definition at line 33 of file 4.3.1.6 LAB A leap year writing your own functions.py.
test_years
list 4.test_years = [1900, 2000, 2016, 1987]
Definition at line 46 of file 4.3.1.7 LAB How many days writing and using your own functions.py.
yr
list 4.yr = test_data[i]
Definition at line 35 of file 4.3.1.6 LAB A leap year writing your own functions.py.