SP-Python-Essentials-DP: mqtt Namespace Reference
mqtt Namespace Reference
Functions
def connect_mqtt ()
def publish (client)
def run ()
Variables
string broker = 'broker.emqx.io'
int port = 1883
string topic = "python/mqtt"
string client_id = f'python-mqtt-{random.randint(0, 1000)}'
Function Documentation
connect_mqtt()
def mqtt.connect_mqtt ()
Definition at line 18 of file mqtt.py.
def connect_mqtt():
    def on_connect(client, userdata, flags, rc):
        if rc == 0:
            print("Connected to MQTT Broker!")
        else:
            print("Failed to connect, return code %d\n", rc)
    client = mqtt_client.Client(client_id)
    client.username_pw_set(username, password)
    client.on_connect = on_connect
    client.connect(broker, port)
    return client
Referenced by run().
publish()
def mqtt.publish (client)
Definition at line 32 of file mqtt.py.
def publish(client):
    msg_count = 0
    while True:
        time.sleep(1)
        msg = f"messages: {msg_count}"
        result = client.publish(topic, msg)
        # result: [0, 1]
        status = result[0]
        if status == 0:
            print(f"Send `{msg}` to topic `{topic}`")
        else:
            print(f"Failed to send message to topic {topic}")
        msg_count += 1
Referenced by run().
run()
def mqtt.run ()
Definition at line 47 of file mqtt.py.
def run():
    client = connect_mqtt()
    client.loop_start()
    publish(client)
References connect_mqtt(), publish(), and run().
Referenced by run().
Variable Documentation
broker
string mqtt.broker = 'broker.emqx.io'
Definition at line 9 of file mqtt.py.
client_id
string mqtt.client_id = f'python-mqtt-{random.randint(0, 1000)}'
Definition at line 13 of file mqtt.py.
port
int mqtt.port = 1883
Definition at line 10 of file mqtt.py.
topic
string mqtt.topic = "python/mqtt"
Definition at line 11 of file mqtt.py.