name: codecov

on: [pull_request_target, issues]

jobs:
  codecov:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
