name: codecov

on: 
  issues:
    types:
      - opened
  push:
    branches:
    - Python-Essentials-1---STUDY-RESOURCES
    - release/*
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
